import * as Promise from "bluebird";
import * as K from "..";
import Workbook = require('./Workbook');
import Saveable = require('./Saveable');
declare class Sheet extends Saveable {
    protected workbook: Workbook;
    protected workbookXml: any;
    protected relationshipXml: any;
    protected id: string;
    xml: any;
    filename: string;
    private static refRegex;
    constructor(workbook: Workbook, workbookXml?: any, relationshipXml?: any);
    load(): Promise<any>;
    getName(): string;
    setName(name: string): void;
    create(): void;
    copyFrom(sheet: Sheet): void;
    setCellValue(rownum: number, colnum: number, cellvalue: string | number, copyCellStyle?: string): any;
    setCellValue(ref: string, cellvalue: string | number, copyCellStyle?: string): any;
    private setValue(cell, cellvalue);
    getCellValue(rownum: number, colnum: number): string | number;
    getCellValue(ref: string): string | number;
    getCellValue(cell: K.Cell): string | number;
    getCellFunction(rownum: number, colnum: number): string | number;
    getCellFunction(ref: string): string | number;
    getCellFunction(cell: K.Cell): string | number;
    private getCell(rownum, colnum);
    private getCell(ref);
    private getCell(cell);
    getRow(rownum: number): Array<string | number>;
    getRow(row: K.Row): Array<string | number>;
    setRow(rownum: number, values: Array<string | number>): void;
    setRow(row: K.Row, values: Array<string | number>): void;
    appendRow(values: Array<string | number>): void;
    getLastRowNumber(): number;
    private getRowXML(rownum);
    toJSON(): {};
    protected addRelationship(): void;
    protected addContentType(): void;
    protected addToWorkbook(): void;
    static intToExcelColumn(col: number): string;
    static excelColumnToInt(ref: string): number;
}
export = Sheet;
